# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b005a61716d3cfb092e9b390eb4025eaa1a3435bbbc37912bbe2412ef00a2c0082712cf8cda2bc8e6031d21ed0f3ae206256d5452d7538d69bb3914d34684177

test:
  secret_key_base: 7cd3abe7baca46fae57f3aa87fc8d1a4d5a626879dafbd3ee5433acb5b3627bedebf28d349e3649f82adc442a8b4e7ed43c15885fd5bdfde2a24eea0d5999c6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
